name: Deploy Bamboo Agent

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build & Deploy via OIDC
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Instala Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Instala Serverless Framework
      - name: Install Serverless Framework
        run: npm install -g serverless

      # 4. Autenticação Segura via Role (OIDC)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::234118421196:role/bamboo-github-poc-ia
          aws-region: us-east-1

      # 5. Faz o Deploy
      - name: Serverless Deploy
        run: npm install -g serverless@3